name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-php:
    name: Install PHP
    runs-on: ubuntu-20.04
    steps:
      - name: Install PHP
        run: |
          sudo apt-get update
          sudo apt -y install software-properties-common
          sudo add-apt-repository ppa:ondrej/php
          sudo apt-get update
          sudo apt -y install php7.4
  create-phar:
    name: Create phar
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build phar
      - run: php index.php -r=~/


