name: Build
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  install-php:
    name: Install PHP
    runs-on: ubuntu-20.04
    steps:
      - name: Install PHP
      - run: sudo apt -y install php7.4
  


